### ISSUE TITLE
XDG config folder problem

### ISSUE THREAD

**Issue by Kirtai** [flathub/org.zdoom.GZDoom#15]
I see that the build file contains the following line

- --persist=.config/gzdoom

Doesn't this force the use of $HOME/.config and ignore the settings of the $XDG_CONFIG_HOME environment variable?

**Comment by Eonfge** [comment]
GZDoom doesn't follow the rules of $XDG_CONFIG_HOME. They have a hardcoded check on the location, ~/.config/gzdoom and they even refer to that if you run GZDoom without a valid wad.

the flag --persist= essentially mounts the flatpak folder on that location, so that you can use GZDoom without me having to open up security sensitive folders. Otherwise, you can't use GZDoom without making some upstream changes.

**Comment by Kirtai** [comment]
Ah, I see. So this is a workaround for GZDoom not following the xdg folder standards. I take it that it won't accept a .config folder in it's private flatpak directory either then.

Sorry about the noise :)

**Comment by Eonfge** [comment]
No shame in asking. Packaging cross-platform games from the '90 is not always the most elegant exercise.

Feel free to ask if you have any other questions

**Comment by HugLifeTiZ** [comment]
There's already a shell script, gzdoom.sh, which loads the lights.pk3 and brightmaps.pk3 files. Why not add in another argument: `-config "$XDG_CONFIG_HOME/gzdoom/gzdoom.ini"` in place of the persistence? The persistence doesn't seem to work on my system for some reason.

**Comment by Eonfge** [comment]
Such a change would not be backwards compatible with the current clients, since `"$XDG_CONFIG_HOME/gzdoom/gzdoom.ini"` becomes `/home/kevin/.var/app/org.zdoom.GZDoom/config/gzdoom/gzdoom.ini`, missing the `.` in the `/config/` path.

Perhaps it's easier to look into why the pass-through doesn't work. What is your setup?

**Comment by HugLifeTiZ** [comment]
It would not be backwards compatible, but since we are already using a gzdoom.sh script, we could add logic to migrate old configuration to new configuration if old configuration exists.

It may indeed be easier, but also maybe not. In any case, my `~/.config` is a symlink to `~/xdg/config`, and my `~/.local` is a symlink to `~/xdg`, which has the `share` subfolder that some expect to be there. What's really strange is that even if I don't explicitly grant access to `xdg-config/gzdoom`, it can still see `~/xdg/config/gzdoom` just fine. But within the sandbox, `~/.config` doesn't exist at all:

```
Aura ~ $ flatpak run --command=bash org.zdoom.GZDoom
[📦 org.zdoom.GZDoom ~]$ ls .config
ls: cannot access '.config': No such file or directory
[📦 org.zdoom.GZDoom ~]$ ls xdg/config/gzdoom
gfx-dgpu.cfg  gfx-igpu.cfg  gfx-wolf.cfg  gzdoom.ini  wolf3d.ini
```

It could be that flatpak's persistence logic is resolving the symlink, but GZDoom itself is insisting on trying to read `~/.config/gzdoom`. Which is why I can get around it by explicitly setting a config file via command line.
