### ISSUE TITLE
Hexen crashes - "Could not find patch set" 

### ISSUE THREAD

**Issue by Crazy-bat11** [flathub/org.zdoom.GZDoom#56]
Hi, Just tested every IWAD I have and the only one I am having problem is with Hexen. Below is the error message I get:

Could not find patch set /usr/share/sounds/sf2/FluidR3_GS.sf2.

Could not find patch set /usr/share/sounds/sf2/FluidR3_GM.sf2.

*** Fatal Error ***
!!! Failed to exec debug process
/app/bin/gzdoom.sh, linha 2:     3 Falha de segmentação  (imagem do núcleo gravada)gzdoom +fluid_patchset /app/share/sounds/sf2/gzdoom.sf2 -file lights.pk3 brightmaps.pk3 "$@"

Edited:
I just checked and I have both soundfonts in  "/usr/share/sounds/sf2/". I also tried running Hexen again after adding this path in Flatseal filesystem, but I got the same error message.

**Comment by Eonfge** [comment]
Hey, this issue has come up before. Right now, SoundFonts are not bundled because they're very big, and I don't really want to change that.

How to fix your problem? Install the sound-fonts in your .config folder. See here for details:

https://github.com/flathub/org.zdoom.GZDoom/issues/38#issuecomment-1047203080
